"""Validated learning-based brain extraction (HD-BET or FreeSurfer SynthStrip)."""

# Run external terminal commands like HD-BET
import subprocess
# Handle filesystem paths safely across operating systems
from pathlib import Path
# Type hint for returning a tuple of arrays
from typing import Tuple

# Load and inspect NIfTI neuroimaging files
import nibabel as nib
# Perform array math and boolean mask operations
import numpy as np


# Custom exception raised when brain extraction fails
class BrainExtractionError(RuntimeError):
    pass


import shutil
import sys


def _resolve_executable(name: str) -> str:
    """Find executable in PATH or the active Python virtual environment."""
    found = shutil.which(name)
    if found:
        return found
    for ext in ("", ".exe", ".bat", ".cmd"):
        candidate = Path(sys.prefix) / "Scripts" / f"{name}{ext}"
        if candidate.is_file():
            return str(candidate)
    return name


# Execute a terminal command and catch errors
def _run(command: list[str]) -> None:
    resolved_cmd = [_resolve_executable(command[0])] + list(command[1:])
    try:
        completed = subprocess.run(resolved_cmd, check=False, capture_output=True, text=True)
    except FileNotFoundError as exc:
        raise BrainExtractionError(
            f"Brain extractor executable '{command[0]}' was not found. Install HD-BET "
            "(pip install hd-bet) or FreeSurfer SynthStrip and ensure it is on PATH."
        ) from exc
    if completed.returncode:
        detail = (completed.stderr or completed.stdout or "no diagnostic output").strip()
        raise BrainExtractionError(f"Extractor exited {completed.returncode}: {detail[-4000:]}")


# Extract brain tissue (removes skull, eyes, neck) and return stripped volume + mask
def extract_brain(input_nifti: str | Path, work_dir: str | Path,
                  extractor: str = "hd-bet", device: str = "auto",
                  disable_tta: bool = False) -> Tuple[np.ndarray, np.ndarray]:
    # Convert input scan path to a Path object
    input_path = Path(input_nifti)
    # Convert temporary working directory path to a Path object
    work = Path(work_dir)
    # Create the temporary working directory if it does not exist
    work.mkdir(parents=True, exist_ok=True)
    # Define expected path for the skull-stripped brain volume
    brain_path = work / "brain.nii.gz"
    # Define expected path for the binary brain mask
    mask_path = work / "brain_mask.nii.gz"

    # Handle HD-BET neural network brain extraction
    if extractor == "hd-bet":
        # Build base HD-BET CLI command to save both brain volume and mask
        command = ["hd-bet", "-i", str(input_path), "-o", str(brain_path),
                   "--save_bet_mask"]
        # Store requested device setting (auto, cuda, or cpu)
        resolved_device = device
        # Automatically detect if an NVIDIA GPU is available
        if resolved_device == "auto":
            try:
                import torch
                resolved_device = "cuda" if torch.cuda.is_available() else "cpu"
            except ImportError:
                resolved_device = "cpu"
        # Append target computing device to the command
        command += ["-device", resolved_device]
        # Disable test-time augmentation on CPU to run 4x faster
        if disable_tta or resolved_device == "cpu":
            command.append("--disable_tta")
        # Run the HD-BET extraction command
        _run(command)
        # Verify that HD-BET actually created the brain image
        if not brain_path.is_file():
            raise BrainExtractionError(f"HD-BET did not produce expected image: {brain_path}")
        # Locate the mask file generated by HD-BET in the work folder
        candidates = sorted(p for p in work.glob("*.nii*")
                            if p != brain_path and ("mask" in p.name.lower()
                                                    or p.name.lower().endswith("_bet.nii.gz")))
        # Ensure exactly one valid mask file was generated
        if len(candidates) != 1:
            raise BrainExtractionError(
                f"HD-BET should produce one mask with --save_bet_mask; found {[p.name for p in candidates]}"
            )
        # Select the identified mask file path
        mask_path = candidates[0]
    # Handle FreeSurfer SynthStrip alternative extractor
    elif extractor == "synthstrip":
        # Build command for FreeSurfer SynthStrip tool
        command = ["mri_synthstrip", "-i", str(input_path), "-o", str(brain_path),
                   "-m", str(mask_path), "--no-csf"]
        # Run SynthStrip command
        _run(command)
        # Verify that SynthStrip generated both brain and mask files
        if not brain_path.is_file() or not mask_path.is_file():
            raise BrainExtractionError("SynthStrip did not produce both brain image and mask")
    # Reject unsupported extractor names
    else:
        raise ValueError("extractor must be 'hd-bet' or 'synthstrip'")

    # Load the original input scan to verify spatial geometry
    source = nib.load(str(input_path))
    # Load the newly created skull-stripped brain volume
    brain_img = nib.load(str(brain_path))
    # Load the newly created binary brain mask
    mask_img = nib.load(str(mask_path))
    # Check that output 3D dimensions match the input dimensions exactly
    if brain_img.shape != source.shape or mask_img.shape != source.shape:
        raise BrainExtractionError("Extractor output dimensions do not match the input")
    # Verify that the physical coordinates of the brain image were not shifted
    if not np.allclose(brain_img.affine, source.affine, atol=1e-4):
        raise BrainExtractionError("Extractor brain image changed input voxel geometry")
    # Verify that the physical coordinates of the mask match the input scan
    if not np.allclose(mask_img.affine, source.affine, atol=1e-4):
        raise BrainExtractionError("Extractor mask changed input voxel geometry")
    # Convert mask values to boolean array (True = brain, False = background)
    mask = np.asarray(mask_img.dataobj) > 0.5
    # Load brain voxel values as 32-bit float array
    volume = np.asarray(brain_img.dataobj, dtype=np.float32)
    # Check that mask is not empty and volume has no NaN/Inf numbers
    if not mask.any() or not np.isfinite(volume).all():
        raise BrainExtractionError("Extractor returned an empty mask or invalid image values")
    # Zero out any non-brain voxels (ensures background is strictly 0.0)
    volume[~mask] = 0.0
    # Return the clean skull-stripped volume and its binary brain mask
    return volume, mask
